version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
            pip install pipenv
            pipenv install
      - run:
          name: PyTest
          command: |
            pytest
