pipeline {
  agent any

  environment {
    PATH = "C:\\WINDOWS\\SYSTEM32;C:\\Users\\i1A771792\\opt\\python3.8.5"
  }

  stages {
    stage('Build') {
      steps {
        echo 'Building..'
        bat """
        python -m pip install --upgrade pipenv
        python -m pipenv install
        """
      }
    }
    stage('Test') {
      steps {
        echo 'Testing..'
        bat """
        python -m pipenv run "jenkins\\windows\\tests.bat"
        """
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }
  }

  post {
    always {
      junit "reports/*.xml"
      archiveArtifacts artifacts: 'reports/*.xml', fingerprint: true
    }
  }
}
