pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        echo 'Building..'
      }
    }
    stage('Test') {
      steps {
        echo 'Testing..'
        sh """
        python3 -m pipenv install
        python3 -m pipenv run "jenkins/unix/tests.sh"
        """
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }
  }

  post {
    always {
      junit "reports/*.xml"
    }
  }
}
